Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.insert_key = false
  #config.ssh.forward_agent = true
  config.vm.synced_folder "./", "/vagrant"

 config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
 end

 boxes = [
   { :name => "lb",   :ip => "192.168.56.10" },
   { :name => "web1", :ip => "192.168.56.11" },
   { :name => "web2", :ip => "192.168.56.12" }
]

boxes.each do |opts|
   config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network :private_network, ip: opts[:ip]
   end
 end
end